spring:
  application:
    name: simple-transit

  jpa:
    defer-datasource-initialization: false

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password

  h2:
    console:
      enabled: true

jwt:
  access-token:
    secret: 91b48677c9ef80389925ba4f5f2ff8e9
    expiration-time: 3600
  refresh-token:
    expiration-time: 7200
  issuer: tivic-simple-transit
